package familiar.domain.character.witcher.profession;

import familiar.domain.character.witcher.wStats;

public enum wProfessionSkills {

    //BARD
    BUSKING(wStats.EMPATHY, null),
    RETURNACT(wStats.EMPATHY, BUSKING),
    RAISEACROWD(wStats.EMPATHY, RETURNACT),
    GOODFRIEND(wStats.EMPATHY, RAISEACROWD),
    FADE(wStats.INTELLIGENCE, BUSKING),
    SPREADTHEWORD(wStats.INTELLIGENCE, FADE),
    ACCLIMATIZE(wStats.INTELLIGENCE, SPREADTHEWORD),
    POISONTHEWELL(wStats.EMPATHY, BUSKING),
    NEEDLING(wStats.EMPATHY, POISONTHEWELL),
    ETTUBRUTE(wStats.EMPATHY, NEEDLING),

    //CRAFTSMAN
    PATCHJOB(wStats.CRAFT, null),
    EXTENSIVECATALOGUE(wStats.INTELLIGENCE, PATCHJOB),
    JOURNEYMAN(wStats.CRAFT, EXTENSIVECATALOGUE),
    MASTERCRAFTING(wStats.CRAFT, JOURNEYMAN),
    MENTALPHARMACY(wStats.INTELLIGENCE, PATCHJOB),
    DOUBLEDOSE(wStats.CRAFT, MENTALPHARMACY),
    ADAPTATION(wStats.CRAFT, DOUBLEDOSE),
    AUGMENTATION(wStats.CRAFT, PATCHJOB),
    SILVERCOATING(wStats.CRAFT, AUGMENTATION),
    PINPOINT(wStats.CRAFT, SILVERCOATING),

    //CRIMINAL
    PRACTICEDPARANOIA(wStats.INTELLIGENCE, null),
    CASETHEAREA(wStats.INTELLIGENCE, PRACTICEDPARANOIA),
    MENTALKEY(wStats.INTELLIGENCE, CASETHEAREA),
    GOTOGROUND(wStats.INTELLIGENCE, MENTALKEY),
    WEAKSPOT(wStats.EMPATHY, PRACTICEDPARANOIA),
    MARKEDMAN(wStats.WILL, WEAKSPOT),
    RALLY(wStats.WILL, MARKEDMAN),
    CAREFULAIM(wStats.DEXTERITY, PRACTICEDPARANOIA),
    EYEGOUGE(wStats.DEXTERITY, CAREFULAIM),
    ASSASSINSSTRIKE(wStats.DEXTERITY, EYEGOUGE),

    //DOCTOR

    HEALINGHANDS(wStats.CRAFT, null),
    DIAGNOSE(wStats.INTELLIGENCE, HEALINGHANDS),
    ANALYSIS(wStats.INTELLIGENCE, DIAGNOSE),
    EFFECTIVESURGERY(wStats.CRAFT, ANALYSIS),
    HEALINGTENT(wStats.CRAFT, HEALINGHANDS),
    IMPROVISATION(wStats.INTELLIGENCE, HEALINGTENT),
    HERBALREMEDY(wStats.CRAFT, IMPROVISATION),
    BLEEDINGWOUND(wStats.INTELLIGENCE, HEALINGHANDS),
    PRACTICALCARNAGE(wStats.INTELLIGENCE, BLEEDINGWOUND),
    CRIPPLINGWOUND(wStats.INTELLIGENCE, PRACTICALCARNAGE),

    //MAGE

    MAGICALTRAINING(wStats.INTELLIGENCE, null),
    SCHEMING(wStats.INTELLIGENCE, MAGICALTRAINING),
    GRAPEVINE(wStats.INTELLIGENCE, SCHEMING),
    ASSETS(wStats.INTELLIGENCE, GRAPEVINE),
    REVERSEENGINEER(wStats.INTELLIGENCE, MAGICALTRAINING),
    DISTILLATION(wStats.CRAFT, REVERSEENGINEER),
    MUTATE(wStats.INTELLIGENCE, DISTILLATION),
    INTOUCH(wStats.NULL, MAGICALTRAINING),
    IMMUTABLE(wStats.WILL, INTOUCH),
    EXPANDEDMAGIC(wStats.WILL, IMMUTABLE),

    //MANATARMS
    TOUGHASNAILS(wStats.BODY, null),
    EXTREMERANGE(wStats.DEXTERITY, TOUGHASNAILS),
    TWINSHOT(wStats.DEXTERITY, EXTREMERANGE),
    PINPOINTAIM(wStats.DEXTERITY, TWINSHOT),
    BLOODHOUND(wStats.INTELLIGENCE, TOUGHASNAILS),
    BOOBYTRAP(wStats.CRAFT, BLOODHOUND),
    TACTICALAWARENESS(wStats.INTELLIGENCE, BOOBYTRAP),
    FURY(wStats.WILL, TOUGHASNAILS),
    ZWEIHAND(wStats.BODY, FURY),
    SHRUGITOFF(wStats.BODY, ZWEIHAND),

    //MERCHANT
    WELLTRAVELED(wStats.INTELLIGENCE, null),
    OPTIONS(wStats.INTELLIGENCE, WELLTRAVELED),
    HARDBARGAIN(wStats.EMPATHY, OPTIONS),
    PROMISE(wStats.EMPATHY, HARDBARGAIN),
    ROOKERY(wStats.EMPATHY, WELLTRAVELED),
    INSIDER(wStats.INTELLIGENCE, ROOKERY),
    TREASUREMAP(wStats.INTELLIGENCE, INSIDER),
    WELLCONNECTED(wStats.WILL, WELLTRAVELED),
    FENCE(wStats.INTELLIGENCE, WELLCONNECTED),
    WARRIORSDEPT(wStats.EMPATHY, FENCE),

    //PRIEST
    INITIATEOFTHEGODS(wStats.EMPATHY, null),
    DIVINEPOWER(wStats.EMPATHY, INITIATEOFTHEGODS),
    DIVINEAUTHORITY(wStats.EMPATHY, DIVINEPOWER),
    PRECOGNITION(wStats.WILL, DIVINEAUTHORITY),
    NATUREATTUNEMENT(wStats.NULL, INITIATEOFTHEGODS),
    READNATURE(wStats.NULL, NATUREATTUNEMENT),
    ANIMALCOMPACT(wStats.WILL, READNATURE),
    BLOODRITUALS(wStats.WILL, INITIATEOFTHEGODS),
    FERVOR(wStats.EMPATHY, BLOODRITUALS),
    WORDOFGOD(wStats.EMPATHY, FERVOR),

    //WITCHER
    WITCHERTRAINING(wStats.INTELLIGENCE, null),
    MEDITATION(wStats.NULL, WITCHERTRAINING),
    MAGICALSOURCE(wStats.NULL, MEDITATION),
    HELIOTROPE(wStats.WILL, MAGICALSOURCE),
    IRONSTOMACH(wStats.NULL, WITCHERTRAINING),
    FRENZY(wStats.NULL, IRONSTOMACH),
    TRANSMUTATION(wStats.BODY, FRENZY),
    PARRYARROWS(wStats.DEXTERITY, WITCHERTRAINING),
    QUICKSTRIKE(wStats.REFLEXES, PARRYARROWS),
    WHIRL(wStats.REFLEXES, QUICKSTRIKE);

    public final wStats baseAbility;
    public final wProfessionSkills preRequisite;

    wProfessionSkills(wStats baseAbility, wProfessionSkills preRequisite) {
        this.baseAbility = baseAbility;
        this.preRequisite = preRequisite;
    }


}
