package familiar.domain.character.witcher.profession;

import familiar.domain.character.witcher.wAbilities;

public enum wProfessionSkills {

    //BARD
    BUSKING(wAbilities.EMPATHY, null),
    RETURNACT(wAbilities.EMPATHY, BUSKING),
    RAISEACROWD(wAbilities.EMPATHY, RETURNACT),
    GOODFRIEND(wAbilities.EMPATHY, RAISEACROWD),
    FADE(wAbilities.INTELLIGENCE, BUSKING),
    SPREADTHEWORD(wAbilities.INTELLIGENCE, FADE),
    ACCLIMATIZE(wAbilities.INTELLIGENCE, SPREADTHEWORD),
    POISONTHEWELL(wAbilities.EMPATHY, BUSKING),
    NEEDLING(wAbilities.EMPATHY, POISONTHEWELL),
    ETTUBRUTE(wAbilities.EMPATHY, NEEDLING),

    //CRAFTSMAN
    PATCHJOB(wAbilities.CRAFT, null),
    EXTENSIVECATALOGUE(wAbilities.INTELLIGENCE, PATCHJOB),
    JOURNEYMAN(wAbilities.CRAFT, EXTENSIVECATALOGUE),
    MASTERCRAFTING(wAbilities.CRAFT, JOURNEYMAN),
    MENTALPHARMACY(wAbilities.INTELLIGENCE, PATCHJOB),
    DOUBLEDOSE(wAbilities.CRAFT, MENTALPHARMACY),
    ADAPTATION(wAbilities.CRAFT, DOUBLEDOSE),
    AUGMENTATION(wAbilities.CRAFT, PATCHJOB),
    SILVERCOATING(wAbilities.CRAFT, AUGMENTATION),
    PINPOINT(wAbilities.CRAFT, SILVERCOATING),

    //CRIMINAL
    PRACTICEDPARANOIA(wAbilities.INTELLIGENCE, null),
    CASETHEAREA(wAbilities.INTELLIGENCE, PRACTICEDPARANOIA),
    MENTALKEY(wAbilities.INTELLIGENCE, CASETHEAREA),
    GOTOGROUND(wAbilities.INTELLIGENCE, MENTALKEY),
    WEAKSPOT(wAbilities.EMPATHY, PRACTICEDPARANOIA),
    MARKEDMAN(wAbilities.WILL, WEAKSPOT),
    RALLY(wAbilities.WILL, MARKEDMAN),
    CAREFULAIM(wAbilities.DEXTERITY, PRACTICEDPARANOIA),
    EYEGOUGE(wAbilities.DEXTERITY, CAREFULAIM),
    ASSASSINSSTRIKE(wAbilities.DEXTERITY, EYEGOUGE),

    //DOCTOR

    HEALINGHANDS(wAbilities.CRAFT, null),
    DIAGNOSE(wAbilities.INTELLIGENCE, HEALINGHANDS),
    ANALYSIS(wAbilities.INTELLIGENCE, DIAGNOSE),
    EFFECTIVESURGERY(wAbilities.CRAFT, ANALYSIS),
    HEALINGTENT(wAbilities.CRAFT, HEALINGHANDS),
    IMPROVISATION(wAbilities.INTELLIGENCE, HEALINGTENT),
    HERBALREMEDY(wAbilities.CRAFT, IMPROVISATION),
    BLEEDINGWOUND(wAbilities.INTELLIGENCE, HEALINGHANDS),
    PRACTICALCARNAGE(wAbilities.INTELLIGENCE, BLEEDINGWOUND),
    CRIPPLINGWOUND(wAbilities.INTELLIGENCE, PRACTICALCARNAGE),

    //MAGE

    MAGICALTRAINING(wAbilities.INTELLIGENCE, null),
    SCHEMING(wAbilities.INTELLIGENCE, MAGICALTRAINING),
    GRAPEVINE(wAbilities.INTELLIGENCE, SCHEMING),
    ASSETS(wAbilities.INTELLIGENCE, GRAPEVINE),
    REVERSEENGINEER(wAbilities.INTELLIGENCE, MAGICALTRAINING),
    DISTILLATION(wAbilities.CRAFT, REVERSEENGINEER),
    MUTATE(wAbilities.INTELLIGENCE, DISTILLATION),
    INTOUCH(null, MAGICALTRAINING),
    IMMUTABLE(wAbilities.WILL, INTOUCH),
    EXPANDEDMAGIC(wAbilities.WILL, IMMUTABLE),

    //MANATARMS
    TOUGHASNAILS(wAbilities.BODY, null),
    EXTREMERANGE(wAbilities.DEXTERITY, TOUGHASNAILS),
    TWINSHOT(wAbilities.DEXTERITY, EXTREMERANGE),
    PINPOINTAIM(wAbilities.DEXTERITY, TWINSHOT),
    BLOODHOUND(wAbilities.INTELLIGENCE, TOUGHASNAILS),
    BOOBYTRAP(wAbilities.CRAFT, BLOODHOUND),
    TACTICALAWARENESS(wAbilities.INTELLIGENCE, BOOBYTRAP),
    FURY(wAbilities.WILL, TOUGHASNAILS),
    ZWEIHAND(wAbilities.BODY, FURY),
    SHRUGITOFF(wAbilities.BODY, ZWEIHAND),

    //MERCHANT
    WELLTRAVELED(wAbilities.INTELLIGENCE, null),
    OPTIONS(wAbilities.INTELLIGENCE, WELLTRAVELED),
    HARDBARGAIN(wAbilities.EMPATHY, OPTIONS),
    PROMISE(wAbilities.EMPATHY, HARDBARGAIN),
    ROOKERY(wAbilities.EMPATHY, WELLTRAVELED),
    INSIDER(wAbilities.INTELLIGENCE, ROOKERY),
    TREASUREMAP(wAbilities.INTELLIGENCE, INSIDER),
    WELLCONNECTED(wAbilities.WILL, WELLTRAVELED),
    FENCE(wAbilities.INTELLIGENCE, WELLCONNECTED),
    WARRIORSDEPT(wAbilities.EMPATHY, FENCE),

    //PRIEST
    INITIATEOFTHEGODS(wAbilities.EMPATHY, null),
    DIVINEPOWER(wAbilities.EMPATHY, INITIATEOFTHEGODS),
    DIVINEAUTHORITY(wAbilities.EMPATHY, DIVINEPOWER),
    PRECOGNITION(wAbilities.WILL, DIVINEAUTHORITY),
    NATUREATTUNEMENT(null, INITIATEOFTHEGODS),
    READNATURE(null, NATUREATTUNEMENT),
    ANIMALCOMPACT(wAbilities.WILL, READNATURE),
    BLOODRITUALS(wAbilities.WILL, INITIATEOFTHEGODS),
    FERVOR(wAbilities.EMPATHY, BLOODRITUALS),
    WORDOFGOD(wAbilities.EMPATHY, FERVOR),

    //WITCHER
    WITCHERTRAINING(wAbilities.INTELLIGENCE, null),
    MEDITATION(null, WITCHERTRAINING),
    MAGICALSOURCE(null, MEDITATION),
    HELIOTROPE(wAbilities.WILL, MAGICALSOURCE),
    IRONSTOMACH(null, WITCHERTRAINING),
    FRENZY(null, IRONSTOMACH),
    TRANSMUTATION(wAbilities.BODY, FRENZY),
    PARRYARROWS(wAbilities.DEXTERITY, WITCHERTRAINING),
    QUICKSTRIKE(wAbilities.REFLEXES, PARRYARROWS),
    WHIRL(wAbilities.REFLEXES, QUICKSTRIKE);

    wProfessionSkills(wAbilities empathy, wProfessionSkills preRequisite) {
    }
}
