package familiar.domain.character.witcher;

public enum wSkills {
    AWARENESS(wAbilities.Intelligence, 1),
    BUSINESS(wAbilities.Intelligence, 1),
    DEDUCTION(wAbilities.Intelligence, 1),
    EDUCATION(wAbilities.Intelligence, 1),
    LANGUAGE(wAbilities.Intelligence, 2),
    MONSTERLORE(wAbilities.Intelligence, 2),
    SOCIALETIQUETTE(wAbilities.Intelligence, 1),
    STREETWISE(wAbilities.Intelligence, 1),
    TACTICS(wAbilities.Intelligence, 2),
    TEACHING(wAbilities.Intelligence, 1),
    WILDERNESSSURVIVAL(wAbilities.Intelligence, 1),
    BRAWLING(wAbilities.Reflexes, 1),
    DODGEESCAPE(wAbilities.Reflexes, 1),
    MELEE(wAbilities.Reflexes, 1),
    RIDING(wAbilities.Reflexes, 1),
    SAILING(wAbilities.Reflexes, 1),
    SMALLBLADES(wAbilities.Reflexes, 1),
    STAFFSPEAR(wAbilities.Reflexes, 1),
    SWORDSMANSHIP(wAbilities.Reflexes, 1),
    ARCHERY(wAbilities.Dexterity, 1),
    ATHLETICS(wAbilities.Dexterity, 1),
    CROSSBOW(wAbilities.Dexterity, 1),
    SLEIGHTOFHAND(wAbilities.Dexterity, 1),
    STEALTH(wAbilities.Dexterity, 1),
    PHYSIQUE(wAbilities.Body, 1),
    ENDURANCE(wAbilities.Body, 1),
    CHARISMA(wAbilities.Empathy, 1),
    DECEIT(wAbilities.Empathy, 1),
    FINEARTS(wAbilities.Empathy, 1),
    GAMBLING(wAbilities.Empathy, 1),
    GROOMINGANDSTYLE(wAbilities.Empathy, 1),
    HUMANPERCEPTION(wAbilities.Empathy, 1),
    LEADERSHIP(wAbilities.Empathy, 1),
    PERSUASION(wAbilities.Empathy, 1),
    PERFORMANCE(wAbilities.Empathy, 1),
    SEDUCTION(wAbilities.Empathy, 1),
    ALCHEMY(wAbilities.Craft, 2),
    CRAFTING(wAbilities.Craft, 2),
    DISGUISE(wAbilities.Craft, 1),
    FIRSTAID(wAbilities.Craft, 1),
    FORGERY(wAbilities.Craft, 1),
    PICKLOCK(wAbilities.Craft, 1),
    TRAPCRAFTING(wAbilities.Craft, 2),
    COURAGE(wAbilities.Will, 1),
    HEXWEAVING(wAbilities.Will, 2),
    INTIMIDATION(wAbilities.Will, 1),
    SPELLCASTING(wAbilities.Will, 2),
    RESISTMAGIC(wAbilities.Will, 2),
    RESISTCOERCION(wAbilities.Will, 1),
    RITUALCRAFTING(wAbilities.Will, 2);

    wSkills(wAbilities ability, int multiplier) {

    }
}
