package familiar.domain.character.witcher;

public enum wSkills {
    Awareness(wAbilities.Intelligence, 1),
    Business(wAbilities.Intelligence, 1),
    Deduction(wAbilities.Intelligence, 1),
    Education(wAbilities.Intelligence, 1),
    Language(wAbilities.Intelligence, 2),
    MonsterLore(wAbilities.Intelligence, 2),
    SocialEtiquette(wAbilities.Intelligence, 1),
    Streetwise(wAbilities.Intelligence, 1),
    Tactics(wAbilities.Intelligence, 2),
    Teaching(wAbilities.Intelligence, 1),
    WildernessSurvival(wAbilities.Intelligence, 1),
    Brawling(wAbilities.Reflexes, 1),
    DodgeEscape(wAbilities.Reflexes, 1),
    Melee(wAbilities.Reflexes, 1),
    Riding(wAbilities.Reflexes, 1),
    Sailing(wAbilities.Reflexes, 1),
    SmallBlades(wAbilities.Reflexes, 1),
    StaffSpear(wAbilities.Reflexes, 1),
    Swordsmanship(wAbilities.Reflexes, 1),
    Archery(wAbilities.Dexterity, 1),
    Athletics(wAbilities.Dexterity, 1),
    Crossbow(wAbilities.Dexterity, 1),
    SleightOfHand(wAbilities.Dexterity, 1),
    Stealth(wAbilities.Dexterity, 1),
    Physique(wAbilities.Body, 1),
    Endurance(wAbilities.Body, 1),
    Charisma(wAbilities.Empathy, 1),
    Deceit(wAbilities.Empathy, 1),
    FineArts(wAbilities.Empathy, 1),
    Gambling(wAbilities.Empathy, 1),
    GroomingAndStyle(wAbilities.Empathy, 1),
    HumanPerception(wAbilities.Empathy, 1),
    Leadership(wAbilities.Empathy, 1),
    Persuasion(wAbilities.Empathy, 1),
    Performance(wAbilities.Empathy, 1),
    Seduction(wAbilities.Empathy, 1),
    Alchemy(wAbilities.Craft, 2),
    Crafting(wAbilities.Craft, 2),
    Disguise(wAbilities.Craft, 1),
    FirstAid(wAbilities.Craft, 1),
    Forgery(wAbilities.Craft, 1),
    PickLock(wAbilities.Craft, 1),
    TrapCrafting(wAbilities.Craft, 2),
    Courage(wAbilities.Will, 1),
    HexWeaving(wAbilities.Will, 2),
    Intimidation(wAbilities.Will, 1),
    SpellCasting(wAbilities.Will, 2),
    ResistMagic(wAbilities.Will, 2),
    ResistCoercion(wAbilities.Will, 1),
    RitualCrafting(wAbilities.Will, 2);

    wSkills(wAbilities ability, int multiplier) {

    }
}
