package familiar.service.character.domain.witcher.profession;


import familiar.service.character.domain.witcher.WitcherStats;

public enum WitcherProfessionSkills {

    //BARD
    BUSKING(WitcherStats.EMPATHY, null),
    RETURNACT(WitcherStats.EMPATHY, BUSKING),
    RAISEACROWD(WitcherStats.EMPATHY, RETURNACT),
    GOODFRIEND(WitcherStats.EMPATHY, RAISEACROWD),
    FADE(WitcherStats.INTELLIGENCE, BUSKING),
    SPREADTHEWORD(WitcherStats.INTELLIGENCE, FADE),
    ACCLIMATIZE(WitcherStats.INTELLIGENCE, SPREADTHEWORD),
    POISONTHEWELL(WitcherStats.EMPATHY, BUSKING),
    NEEDLING(WitcherStats.EMPATHY, POISONTHEWELL),
    ETTUBRUTE(WitcherStats.EMPATHY, NEEDLING),

    //CRAFTSMAN
    PATCHJOB(WitcherStats.CRAFT, null),
    EXTENSIVECATALOGUE(WitcherStats.INTELLIGENCE, PATCHJOB),
    JOURNEYMAN(WitcherStats.CRAFT, EXTENSIVECATALOGUE),
    MASTERCRAFTING(WitcherStats.CRAFT, JOURNEYMAN),
    MENTALPHARMACY(WitcherStats.INTELLIGENCE, PATCHJOB),
    DOUBLEDOSE(WitcherStats.CRAFT, MENTALPHARMACY),
    ADAPTATION(WitcherStats.CRAFT, DOUBLEDOSE),
    AUGMENTATION(WitcherStats.CRAFT, PATCHJOB),
    SILVERCOATING(WitcherStats.CRAFT, AUGMENTATION),
    PINPOINT(WitcherStats.CRAFT, SILVERCOATING),

    //CRIMINAL
    PRACTICEDPARANOIA(WitcherStats.INTELLIGENCE, null),
    CASETHEAREA(WitcherStats.INTELLIGENCE, PRACTICEDPARANOIA),
    MENTALKEY(WitcherStats.INTELLIGENCE, CASETHEAREA),
    GOTOGROUND(WitcherStats.INTELLIGENCE, MENTALKEY),
    WEAKSPOT(WitcherStats.EMPATHY, PRACTICEDPARANOIA),
    MARKEDMAN(WitcherStats.WILL, WEAKSPOT),
    RALLY(WitcherStats.WILL, MARKEDMAN),
    CAREFULAIM(WitcherStats.DEXTERITY, PRACTICEDPARANOIA),
    EYEGOUGE(WitcherStats.DEXTERITY, CAREFULAIM),
    ASSASSINSSTRIKE(WitcherStats.DEXTERITY, EYEGOUGE),

    //DOCTOR

    HEALINGHANDS(WitcherStats.CRAFT, null),
    DIAGNOSE(WitcherStats.INTELLIGENCE, HEALINGHANDS),
    ANALYSIS(WitcherStats.INTELLIGENCE, DIAGNOSE),
    EFFECTIVESURGERY(WitcherStats.CRAFT, ANALYSIS),
    HEALINGTENT(WitcherStats.CRAFT, HEALINGHANDS),
    IMPROVISATION(WitcherStats.INTELLIGENCE, HEALINGTENT),
    HERBALREMEDY(WitcherStats.CRAFT, IMPROVISATION),
    BLEEDINGWOUND(WitcherStats.INTELLIGENCE, HEALINGHANDS),
    PRACTICALCARNAGE(WitcherStats.INTELLIGENCE, BLEEDINGWOUND),
    CRIPPLINGWOUND(WitcherStats.INTELLIGENCE, PRACTICALCARNAGE),

    //MAGE

    MAGICALTRAINING(WitcherStats.INTELLIGENCE, null),
    SCHEMING(WitcherStats.INTELLIGENCE, MAGICALTRAINING),
    GRAPEVINE(WitcherStats.INTELLIGENCE, SCHEMING),
    ASSETS(WitcherStats.INTELLIGENCE, GRAPEVINE),
    REVERSEENGINEER(WitcherStats.INTELLIGENCE, MAGICALTRAINING),
    DISTILLATION(WitcherStats.CRAFT, REVERSEENGINEER),
    MUTATE(WitcherStats.INTELLIGENCE, DISTILLATION),
    INTOUCH(WitcherStats.NULL, MAGICALTRAINING),
    IMMUTABLE(WitcherStats.WILL, INTOUCH),
    EXPANDEDMAGIC(WitcherStats.WILL, IMMUTABLE),

    //MANATARMS
    TOUGHASNAILS(WitcherStats.BODY, null),
    EXTREMERANGE(WitcherStats.DEXTERITY, TOUGHASNAILS),
    TWINSHOT(WitcherStats.DEXTERITY, EXTREMERANGE),
    PINPOINTAIM(WitcherStats.DEXTERITY, TWINSHOT),
    BLOODHOUND(WitcherStats.INTELLIGENCE, TOUGHASNAILS),
    BOOBYTRAP(WitcherStats.CRAFT, BLOODHOUND),
    TACTICALAWARENESS(WitcherStats.INTELLIGENCE, BOOBYTRAP),
    FURY(WitcherStats.WILL, TOUGHASNAILS),
    ZWEIHAND(WitcherStats.BODY, FURY),
    SHRUGITOFF(WitcherStats.BODY, ZWEIHAND),

    //MERCHANT
    WELLTRAVELED(WitcherStats.INTELLIGENCE, null),
    OPTIONS(WitcherStats.INTELLIGENCE, WELLTRAVELED),
    HARDBARGAIN(WitcherStats.EMPATHY, OPTIONS),
    PROMISE(WitcherStats.EMPATHY, HARDBARGAIN),
    ROOKERY(WitcherStats.EMPATHY, WELLTRAVELED),
    INSIDER(WitcherStats.INTELLIGENCE, ROOKERY),
    TREASUREMAP(WitcherStats.INTELLIGENCE, INSIDER),
    WELLCONNECTED(WitcherStats.WILL, WELLTRAVELED),
    FENCE(WitcherStats.INTELLIGENCE, WELLCONNECTED),
    WARRIORSDEPT(WitcherStats.EMPATHY, FENCE),

    //PRIEST
    INITIATEOFTHEGODS(WitcherStats.EMPATHY, null),
    DIVINEPOWER(WitcherStats.EMPATHY, INITIATEOFTHEGODS),
    DIVINEAUTHORITY(WitcherStats.EMPATHY, DIVINEPOWER),
    PRECOGNITION(WitcherStats.WILL, DIVINEAUTHORITY),
    NATUREATTUNEMENT(WitcherStats.NULL, INITIATEOFTHEGODS),
    READNATURE(WitcherStats.NULL, NATUREATTUNEMENT),
    ANIMALCOMPACT(WitcherStats.WILL, READNATURE),
    BLOODRITUALS(WitcherStats.WILL, INITIATEOFTHEGODS),
    FERVOR(WitcherStats.EMPATHY, BLOODRITUALS),
    WORDOFGOD(WitcherStats.EMPATHY, FERVOR),

    //WITCHER
    WITCHERTRAINING(WitcherStats.INTELLIGENCE, null),
    MEDITATION(WitcherStats.NULL, WITCHERTRAINING),
    MAGICALSOURCE(WitcherStats.NULL, MEDITATION),
    HELIOTROPE(WitcherStats.WILL, MAGICALSOURCE),
    IRONSTOMACH(WitcherStats.NULL, WITCHERTRAINING),
    FRENZY(WitcherStats.NULL, IRONSTOMACH),
    TRANSMUTATION(WitcherStats.BODY, FRENZY),
    PARRYARROWS(WitcherStats.DEXTERITY, WITCHERTRAINING),
    QUICKSTRIKE(WitcherStats.REFLEXES, PARRYARROWS),
    WHIRL(WitcherStats.REFLEXES, QUICKSTRIKE);

    public final WitcherStats baseAbility;
    public final WitcherProfessionSkills preRequisite;

    WitcherProfessionSkills(WitcherStats baseAbility, WitcherProfessionSkills preRequisite) {
        this.baseAbility = baseAbility;
        this.preRequisite = preRequisite;
    }


}
